### ISSUE TITLE
TEP IP static pool not created and not assigned to ESXi hosts

### ISSUE THREAD

**Issue by vTrex-BC** [vmware/terraform-provider-vcf#113]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/terraform-provider-vcf/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.6.6

### Terraform Provider

0.7.0

### VMware Cloud Foundation

4.5.2

### Description

For VCF creation a static IP pool for TEP shall be created during VCF bringup incl. NSX.

### Affected Resources or Data Sources

resource "vcf_instance"/nsx/ip_address_pool

### Terraform Configuration

terraform {
  required_providers {
    vcf = {
      source = "vmware/vcf"
    }
  }
}
provider "vcf" {
  cloud_builder_host = var.cloud_builder_host
  cloud_builder_username = var.cloud_builder_username
  cloud_builder_password = var.cloud_builder_password
  allow_unverified_tls = true
}

resource "vcf_instance" "sddc_1" {
  instance_id = var.vcf_instance_id
  dv_switch_version = var.vDS_version
  skip_esx_thumbprint_validation = true
  management_pool_name = var.vcf_management_pool_name
  ceip_enabled = false
  esx_license = var.esx_license_key
  task_name = "workflowconfig/workflowspec-ems.json"
  sddc_manager {
    ip_address = var.sddc_manager_ip
    hostname = var.sddc_manager_hostname
    root_user_credentials {
      username = "root"
      password = var.sddc_manager_password
    }
    second_user_credentials {
      username = "vcf"
      password = var.sddc_manager_secondary_user_password
    }
  }
  ntp_servers = [
    var.ntp_server_ip
  ]
  dns {
    domain = var.dns_domain_name
    name_server = var.dns_server_ip
  }
  network {
    subnet = var.vcf_mgmt_cidr
    vlan_id = var.vcf_mgmt_vlanid
    mtu = var.PG_default_mtu_size
    network_type = "MANAGEMENT"
    gateway = var.vcf_mgmt_gateway
    port_group_key = var.PG_management_name
  }
  network {
    subnet = var.vcf_vm_mgmt_cidr
    vlan_id = var.vcf_vm_mgmt_vlanid
    mtu = var.PG_default_mtu_size
    network_type = "VM_MANAGEMENT"
    gateway = var.vcf_vm_mgmt_gateway
    port_group_key = var.PG_VM_management_name
  }
  network {
    subnet = var.vcf_mgmt_vmotion_cidr
    include_ip_address_ranges {
      start_ip_address = var.vcf_mgmt_vmotion_start_ip
      end_ip_address = var.vcf_mgmt_vmotion_end_ip
    }
    vlan_id = var.vcf_mgmt_vmotion_vlanid
    mtu = var.vDS_mtu_size
    network_type = "VMOTION"
    gateway = var.vcf_mgmt_vmotion_gateway
    port_group_key = var.PG_vMotion_name
  }
  network {
    subnet = var.vcf_mgmt_vsan_cidr
    include_ip_address_ranges {
      start_ip_address = var.vcf_mgmt_vsan_start_ip
      end_ip_address = var.vcf_mgmt_vsan_end_ip
    }
    vlan_id = var.vcf_mgmt_vsan_vlanid
    mtu = var.vDS_mtu_size
    network_type = "VSAN"
    gateway = var.vcf_mgmt_vsan_gateway
    port_group_key = var.PG_vSAN_name
  }
  nsx {
    nsx_manager_size = var.nsx_manager_size
    nsx_manager {
      hostname = var.nsx_manager_node1_hostname
      ip = var.nsx_manager_node1_ip
    }
    root_nsx_manager_password = var.nsx_manager_root_password
    nsx_admin_password = var.nsx_manager_admin_password
    nsx_audit_password = var.nsx_manager_audit_password
    overlay_transport_zone {
      zone_name = var.nsx_overlay_zone_name
      network_name = var.nsx_overlay_network_name
    }
    vip = var.nsx_manager_vip
    vip_fqdn = var.nsx_manager_vip_fqdn
    license = var.nsx_license_key
    transport_vlan_id = var.nsx_transport_vlanid
    ip_address_pool {
      name = var.nsx_ip_pool_name
      description = "TEP IP Pool for Transport Nodes"
      subnet {
        cidr = var.nsx_ip_pool_subnet_cidr
        gateway = var.nsx_ip_pool_subnet_gateway
        ip_address_pool_range {
          start = var.nsx_ip_pool_start_ip
          end = var.nsx_ip_pool_end_ip
          }
        }
    }
  }
  vsan {
    license = var.vsan_license_key
    datastore_name = var.vsan_datastore_name
  }
  dvs {
    mtu = var.vDS_mtu_size
    nioc {
      traffic_type = "VSAN"
      value = "HIGH"
    }
    nioc {
      traffic_type = "VMOTION"
      value = "LOW"
    }
    nioc {
      traffic_type = "VDP"
      value = "LOW"
    }
    nioc {
      traffic_type = "VIRTUALMACHINE"
      value = "HIGH"
    }
    nioc {
      traffic_type = "MANAGEMENT"
      value = "NORMAL"
    }
    nioc {
      traffic_type = "NFS"
      value = "LOW"
    }
    nioc {
      traffic_type = "HBR"
      value = "LOW"
    }
    nioc {
      traffic_type = "FAULTTOLERANCE"
      value = "LOW"
    }
    nioc {
      traffic_type = "ISCSI"
      value = "LOW"
    }
    dvs_name = var.vDS_name
    vmnics = [
      "vmnic0",
      "vmnic1"
    ]
    networks = [
      "MANAGEMENT",
      "VM_MANAGEMENT",
      "VSAN",
      "VMOTION"
    ]
  }
  cluster {
    cluster_name = var.vsphere_cluster_name
    cluster_evc_mode = ""
    resource_pool {
      name = "Mgmt-ResourcePool"
      type = "management"
    }
    resource_pool {
      name = "Network-ResourcePool"
      type = "network"
    }
    resource_pool {
      name = "Compute-ResourcePool"
      type = "compute"
    }
    resource_pool {
      name = "User-ResourcePool"
      type = "compute"
    }
  }
  psc {
    psc_sso_domain = var.psc_sso_domain
    admin_user_sso_password = var.admin_user_sso_password
  }
  vcenter {
    vcenter_ip = var.vcenter_ip
    vcenter_hostname = var.vcenter_hostname
    license = var.vcenter_license_key
    root_vcenter_password = var.vcenter_root_password
    vm_size = var.vcsa_vm_size
  }
  host {
    credentials {
      username = "root"
      password = var.esx_root_password
    }
    ip_address_private {
      subnet = var.vcf_mgmt_subnet
      cidr = var.vcf_mgmt_cidr
      ip_address = var.esx_host1_ip
      gateway = var.vcf_mgmt_gateway
    }
    hostname = var.esx_host1_hostname
    vswitch = "vSwitch0"
    association = var.vsphere_dc_name
  }
  host {
    credentials {
      username = "root"
      password = var.esx_root_password
    }
    ip_address_private {
      subnet = var.vcf_mgmt_subnet
      cidr = var.vcf_mgmt_cidr
      ip_address = var.esx_host2_ip
      gateway = var.vcf_mgmt_gateway
    }
    hostname = var.esx_host2_hostname
    vswitch = "vSwitch0"
    association = var.vsphere_dc_name
  }
  host {
    credentials {
      username = "root"
      password = var.esx_root_password
    }
    ip_address_private {
      subnet = var.vcf_mgmt_subnet
      cidr = var.vcf_mgmt_cidr
      ip_address = var.esx_host3_ip
      gateway = var.vcf_mgmt_gateway
    }
    hostname = var.esx_host3_hostname
    vswitch = "vSwitch0"
    association = var.vsphere_dc_name
  }
  host {
    credentials {
      username = "root"
      password = var.esx_root_password
    }
    ip_address_private {
      subnet = var.vcf_mgmt_subnet
      cidr = var.vcf_mgmt_cidr
      ip_address = var.esx_host4_ip
      gateway = var.vcf_mgmt_gateway
    }
    hostname = var.esx_host4_hostname
    vswitch = "vSwitch0"
    association = var.vsphere_dc_name
  }
}

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

VCF instance is created incl. SDDC manager, Management-Domain
incl. TEP interfaces with static IP from static IP Pool in NSX

### Actual Behavior

TEP interfaces with DHCP and no static IP Pool in NSX

### Steps to Reproduce

deploy VCF instance with provided file above (variable parameters needed)

**Comment by dimitarproynov** [comment]
Issue has been fixed in v0.8.1
