### ISSUE TITLE
vcf_edge_cluster resource fails with "expected asn to be in the range (1 - -2147483648), got 65004"

### ISSUE THREAD

**Issue by cybernils** [vmware/terraform-provider-vcf#120]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/terraform-provider-vcf/blob/main/CODE_OF_CONDUCT.md).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.7.2

### Terraform Provider

v0.8.0

### VMware Cloud Foundation

v5.0.0.0

### Description

`│ Error: expected asn to be in the range (1 - -2147483648), got 65004
│
│   with vcf_edge_cluster.cluster_1,
│   on main.tf line 19, in resource "vcf_edge_cluster" "cluster_1":
│   19:   asn               = 65004`

### Affected Resources or Data Sources

`resource/vcf_edge_cluster`

### Terraform Configuration

```
resource "vcf_edge_cluster" "cluster_1" {
  name              = var.cluster_name
  root_password     = var.cluster_root_pass
  admin_password    = var.cluster_admin_pass
  audit_password    = var.cluster_audit_pass
  tier0_name        = "Nils-Tier-0"
  tier1_name        = "Nils-Tier-1"
  form_factor       = "MEDIUM"
  profile_type      = "DEFAULT"
  routing_type      = "EBGP"
  high_availability = "ACTIVE_ACTIVE"
  mtu               = 8940
  asn               = 65004
```

### Debug Output

`│ Error: expected asn to be in the range (1 - -2147483648), got 65004
│
│   with vcf_edge_cluster.cluster_1,
│   on main.tf line 19, in resource "vcf_edge_cluster" "cluster_1":
│   19:   asn               = 65004`

### Expected Behavior

Success.

### Actual Behavior

`│ Error: expected asn to be in the range (1 - -2147483648), got 65004
│
│   with vcf_edge_cluster.cluster_1,
│   on main.tf line 19, in resource "vcf_edge_cluster" "cluster_1":
│   19:   asn               = 65004`

### Steps to Reproduce

terraform.exe validate

**Comment by stoyanzhelyazkov** [comment]
Just out of curiousity - Nils, is it possible that you're running Terraform in a 32-bit environment, a VM maybe?

**Comment by cybernils** [comment]
> Just out of curiousity - Nils, is it possible that you're running Terraform in a 32-bit environment, a VM maybe?

Windows Server 2022 Standard.
64-bit operating system, x64-based processor.
Running in a VM on vSphere 8.

**Comment by stoyanzhelyazkov** [comment]
Thanks Nils, glad you have a workaround.
This seems to be a silly mistake on my end.
I will prepare a fix for the x86 binaries and will do my best do get it into the next release

**Comment by cybernils** [comment]
Thanks for your quick response!
