### ISSUE TITLE
Creating a 'vcf_cluster' resource requires parameters which are marked as optional in the vcf-terraform document

### ISSUE THREAD

**Issue by cmsriram** [vmware/terraform-provider-vcf#134]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/terraform-provider-vcf/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.7

### Terraform Provider

VCF provider

### VMware Cloud Foundation

5.1

### Description

While trying to create a VCF cluster with only the mandatory fields as per the VCF terraform document: https://registry.terraform.io/providers/vmware/vcf/latest/docs/resources/cluster, 
the cluster creation  kept failing with a "internal server error:500".
But after following this particular blog exactly with all the fields mentioned here: https://cybernils.net/2024/01/11/using-terraform-to-commission-hosts-and-creating-clusters-in-vcf/, then the VCF cluster creation was successful. 
So logging this issue so that it could be fixed in the VCF terraform provider document.

### Affected Resources or Data Sources

Resource affected is "vcf_cluster"

### Terraform Configuration

Attaching the word doc file which contains the main.tf and variables.tf terraform code copied.

[VCF_Cluster-Creation-TerraformCode.docx](https://github.com/vmware/terraform-provider-vcf/files/14463234/VCF_Cluster-Creation-TerraformCode.docx)

### Debug Output

Dont have access to the debug output now as the lab instance is deleted.
But the exact error was " Internal server error 500" and the API was failing to start executing.

### Expected Behavior

Expected Behavior: The vcf_cluster creation should have been successful with only the required mandatory fields as mentioned in the VCF terraform doc link: https://registry.terraform.io/providers/vmware/vcf/latest/docs/resources/cluster

### Actual Behavior

Actual: The vcf_cluster creation fails when we give only the required fields as per the VCF terraform doc link.

### Steps to Reproduce

1. Create the main.tf and variables.tf file strcitly following the VCF terraform doc link: https://registry.terraform.io/providers/vmware/vcf/latest/docs/resources/cluster providing only the mandatory fields and omitting all the fields mentioned as 'optional' in the above doc link.
2. ON executing the 'terraform apply' command, the vcf_cluster creation errors out on the console with "internal server error code 500" and the API execution fails to start. There is no logging in the logs.

**Comment by stoyanzhelyazkov** [comment]
@cmsriram I replicated the scenario using the configuration you uploaded. I only modified the entity identifiers and names.
My cluster was created successfully. I'm attaching the [console output](https://github.com/vmware/terraform-provider-vcf/files/14495757/working_config_out.txt) for reference.

If you manage to reproduce the issue again please share the log bundle from your SDDC manager appliance. It will help us identify the issue.
