### ISSUE TITLE
Add vmManagementPortgroupName and vmManagementPortgroupVlan to Create Edge Cluster

### ISSUE THREAD

**Issue by vincenthanjs** [vmware/terraform-provider-vcf#147]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

In the VCF API 4.5 onwards, there is option to add vmManagementPortgroupName and vmManagementPortgroupVlan but however its not an option in the terraform provider. Could you please add those in?
https://developer.vmware.com/apis/vcf/latest/v1/edge-clusters/post/

### Use Case(s)

Specify a dedicated management portgroup and vlan for NSX-T Edges in VI Workload Domain. 

### Potential Configuration

 "vmManagementPortgroupName": "string",
 "vmManagementPortgroupVlan": 0

### References

https://developer.vmware.com/apis/vcf/latest/v1/edge-clusters/post/

**Comment by dimitarproynov** [comment]
Hi,

The provider supports VCF 4.5.X as of now. This bug will have to wait until 5.1.X support.

Best Regards

**Comment by vincenthanjs** [comment]
Hi @dimitarproynov,

Actually the VCF 4.5.x API already have the "vmManagementPortgroupName" and "vmManagementPortgroupVlan". Can we make it work for current provider?
