### ISSUE TITLE
vLCM Workload Domain - Create Cluster Spec does not include 'cluster_image_id' when posted to SDDC Manager.

### ISSUE THREAD

**Issue by stevet312** [vmware/terraform-provider-vcf#149]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/terraform-provider-vcf/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.6

### Terraform Provider

0.8.1

### VMware Cloud Foundation

5.1

### Description

When adding additional clusters to an existing Management Workload Domain, the CreateClusterSpec appears to not be passing the 'cluster_image_id' parameter as part of the JSON spec to SDDC Manager.

![Screenshot 2024-04-02 at 5 41 54 PM](https://github.com/vmware/terraform-provider-vcf/assets/30051813/7579f58b-54cb-40e5-9dad-eb3bf28a22d5)

![Screenshot 2024-04-02 at 5 43 23 PM](https://github.com/vmware/terraform-provider-vcf/assets/30051813/ff98e3b1-a3e9-4296-9636-3639c4fa0324)

I can be reached out to internally at VMware on Slack or GChat to reproduce live!

### Affected Resources or Data Sources

resource/vcf_cluster

### Terraform Configuration

https://gist.github.com/stevet312/772728ab2fcaaab51744f431afd7e346

### Debug Output

![Screenshot 2024-04-02 at 6 05 45 PM](https://github.com/vmware/terraform-provider-vcf/assets/30051813/8e825b3e-8ac3-40b9-ac58-1e4f0577c542)

### Expected Behavior

Cluster specs should be posted to SDDC Manager, pass validation and begin creation.,

### Actual Behavior

SDDC Manager fails to validate cluster creation spec due to missing vLCM image id in the POST.

### Steps to Reproduce

1. Available SDDC Manager, completed VCF Bring UP
2. Host commissioning and network pool creation
3. Add UUIDs to TFVARS
4. Attempt to add one or more clusters through the module config

### Environment Details

3 Racks of servers, 12 total hosts
3 Network pools (1 per rack)

VCF 5.1

**Comment by dimitarproynov** [comment]
Hi,

Please see https://github.com/vmware/terraform-provider-vcf/pull/148

Issue has already been addressed and will be released with next release.

**Comment by pradeep17j** [comment]
Is this fix already available in this repo ?
If we pick this repo and do a dev override , we will be able to get this fix ?

**Comment by dimitarproynov** [comment]
Hi @pradeep17j 

Yep, if you pull the current code from "main" and build the provider and setup the dev overrides then the issue should be fixed.

Regards,
_Proynov
