### ISSUE TITLE
`r/csr` fails for `SDDC_MANAGER` and `NSXT_MANAGER`

### ISSUE THREAD

**Issue by smctighevcp** [vmware/terraform-provider-vcf#195]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/terraform-provider-vcf/blob/main/CODE_OF_CONDUCT.md).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.8.5

### Terraform Provider

0.9.1

### VMware Cloud Foundation

5.1

### Description

When attempting to generate a CSR using the resource vcf_csr for SDDC_MANAGER or NSXT_MANAGER it errors reporting that it could not determine the FQDN for the resource type.

Working ok of the VCENTER resource type only.

### Affected Resources or Data Sources

`resource/vcf_csr`

### Terraform Configuration

```hcl
│ # Generate CSR for SDDC Manager - NOT WORKING
│ resource "vcf_csr" "sddc" {
│   resource          = var.vcf_csr_demo.sddc_manager.resource
│   key_size          = var.vcf_csr_demo.sddc_manager.key_size
│  domain_id         = var.vcf_csr_demo.sddc_manager.domain_id
│   organization      = var.vcf_csr_demo.sddc_manager.organization
│   organization_unit = var.vcf_csr_demo.sddc_manager.organization_unit
│   locality          = var.vcf_csr_demo.sddc_manager.locality
│   state             = var.vcf_csr_demo.sddc_manager.state
│   country           = var.vcf_csr_demo.sddc_manager.country
│   email             = var.vcf_csr_demo.sddc_manager.email
│ }

│ # Generate CSR for vCenter - WOKING
│ resource "vcf_csr" "vcenter" {
│  resource          = var.vcf_csr_demo.vcenter.resource
│  key_size          = var.vcf_csr_demo.vcenter.key_size
│  domain_id         = var.vcf_csr_demo.vcenter.domain_id
│ organization      = var.vcf_csr_demo.vcenter.organization
│  organization_unit = var.vcf_csr_demo.vcenter.organization_unit
│  locality          = var.vcf_csr_demo.vcenter.locality
│  state             = var.vcf_csr_demo.vcenter.state
│  country           = var.vcf_csr_demo.vcenter.country
│  email             = var.vcf_csr_demo.vcenter.email
│ }

│ # Generate CSR for NSX Managers - NOT WORKING
│ resource "vcf_csr" "nsxt_manager" {
│   resource          = var.vcf_csr_demo.nsx.resource
│   key_size          = var.vcf_csr_demo.vcenter.key_size
│   domain_id         = var.vcf_csr_demo.vcenter.domain_id
│   organization      = var.vcf_csr_demo.vcenter.organization
│   organization_unit = var.vcf_csr_demo.vcenter.organization_unit
│   locality          = var.vcf_csr_demo.vcenter.locality
│   state             = var.vcf_csr_demo.vcenter.state
│   country           = var.vcf_csr_demo.vcenter.country
│   email             = var.vcf_csr_demo.vcenter.email
│ }
```

### Debug Output

https://gist.github.com/smctighevcp/397826ece0fb478c8caa0093dea26e4d

### Expected Behavior

Should generate a CSR in SDDC for SDDC and NSX-Managers.

### Actual Behavior

Fails as unable to determine FQN for the resource type

```console
│ Error: could not determine FQDN for resourceType NSXT_MANAGER in domain f15d76d5-96e0-4b95-8d4c-46cc93ef3478
│
│   with vcf_csr.nsxt_manager,
│   on main.tf line 28, in resource "vcf_csr" "nsxt_manager":
│   28: resource "vcf_csr" "nsxt_manager" {
```

### Steps to Reproduce

Attempt to generate a CSR for `SDDC_MANAGER` or `NSXT_MANAGER` using `resource/vcf_csr`.

**Comment by spacegospod** [comment]
We dug into this one offline with @smctighevcp 

It appears that `vcf_csr` uses `v1/domains/<domain_id>/endpoints` to determine the FQDN for the provided resource type automatically.
This endpoint only works for resources of type VCENTER since the others are not present in its response.

The correct endpoint to use is `v1/domains/<domain_id>/resource-certificates`. This is the one which the SDDC Manager client relies on.
