### ISSUE TITLE
Add support for `d/vcf_network_pool`

### ISSUE THREAD

**Issue by pradeep17j** [vmware/terraform-provider-vcf#199]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add support for `d/vcf_network_pool`.

If a network pool named "_eng_pool_" is already present you cannot use the following to retrieve the details of the network pool.

```hcl    
  data "vcf_network_pool" "eng_pool" {
       name = "eng_pool"
  }   
```

If we use this block, it fails as below:
  
```console  
Error: Invalid data source

on main.tf line 7, in data "vcf_network_pool" "eng_pool":
7: data "vcf_network_pool" "eng_pool" {

The provider vmware/vcf does not support data source "vcf_network_pool".

Did you intend to use the managed resource type "vcf_network_pool"? If so, declare this using a "resource" block instead of a "data" block.
```

### Use Case(s)

It will be used when data needs to be retrieved from an existing VCF system .

### Potential Configuration

```hcl
  data "vcf_network_pool" "eng_pool" {
       name = "eng_pool"
  }   
```

**Comment by tenthirtyam** [comment]
I've updated this enhancement request to be specific for the `d/vcf_network_pool`.

Please open additional enhancements for other desired data sources.

**Comment by tenthirtyam** [comment]
I've also updated the code blocks and samples to represent the use case.

```hcl
  data "vcf_network_pool" "eng_pool" {
       name = "eng_pool"
  }   
```

**Comment by tenthirtyam** [comment]
Hi @pradeep17j 👋 - 

I have formatted the issue content. We kindly ask that you do the same for future issues.

**Ryan Johnson**
Distinguished Engineer, VMware by Broadcom

**Comment by tenthirtyam** [comment]
Draft pull request: https://github.com/vmware/terraform-provider-vcf/pull/225
