### ISSUE TITLE
Error: REMOVE_HOST operation validation failed

### ISSUE THREAD

**Issue by pradeep17j** [vmware/terraform-provider-vcf#201]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/terraform-provider-vcf/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.9.2

### Terraform Provider

0.9.1

### VMware Cloud Foundation

5.2

### Description

Remove host operation on a cluster fails with error message below.

```console
Message: REMOVE_HOST operation validation failed due to: Cluster HA/DRS: Check if cluster has HA & DRS enabled

Remediation Message:

Reference Token: PJUHO6

Cause: 
```

This happens because the provider by default sets the  `high_availability_enabled": false,`
Below is the snippet of `terraform.tfstate` file which shows that `high_availability_enabled=False`.

The provider should set this to `true`.

```json
{
  "version": 4,
  "terraform_version": "1.9.2",
  "serial": 20,
  "lineage": "1a400f44-29a9-8c66-e115-5f240a8fdca6",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "vcf_domain",
      "name": "workload_domain1",
      "provider": "provider[\"registry.terraform.io/vmware/vcf\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "cluster": [
              {
                "cluster_image_id": "",
                "evc_mode": "",
                "geneve_vlan_id": 200,
                "high_availability_enabled": false,
                "host": [
                  {
```

### Affected Resources or Data Sources

`r/workload_domain`

### Terraform Configuration

```hcl
resource "vcf_domain" "workload_domain1" {
  name = "sfo-w01-vc01"

  #vCenter Settings
  vcenter_configuration {
    name            = var.wld1_vcenter_configuration["name"]
    fqdn            = var.wld1_vcenter_configuration["fqdn"]
    vm_size         = var.wld1_vcenter_configuration["vm_size"]
    storage_size    = var.wld1_vcenter_configuration["storage_size"]
    ip_address      = var.wld1_vcenter_configuration["ip"]
    subnet_mask     = var.wld1_vcenter_configuration["subnet_mask"]
    gateway         = var.wld1_vcenter_configuration["gateway"]
    datacenter_name = "${var.workload_domain1_name}-dc"
    root_password   = var.wld_passwords["vcenter"]
  }
```

### Debug Output

```console
vcf_domain.workload_domain1: Modifying... [id=7eaebd4a-d7da-4de0-81c5-2c53faedefb3]
vcf_domain.workload_domain1: Still modifying... [id=7eaebd4a-d7da-4de0-81c5-2c53faedefb3, 10s elapsed]
vcf_domain.workload_domain1: Still modifying... [id=7eaebd4a-d7da-4de0-81c5-2c53faedefb3, 20s elapsed]
vcf_domain.workload_domain1: Still modifying... [id=7eaebd4a-d7da-4de0-81c5-2c53faedefb3, 30s elapsed]
vcf_domain.workload_domain1: Still modifying... [id=7eaebd4a-d7da-4de0-81c5-2c53faedefb3, 40s elapsed]
vcf_domain.workload_domain1: Still modifying... [id=7eaebd4a-d7da-4de0-81c5-2c53faedefb3, 50s elapsed]
vcf_domain.workload_domain1: Still modifying... [id=7eaebd4a-d7da-4de0-81c5-2c53faedefb3, 1m0s elapsed]
╷
│ Error: Task with ID = e2ece250-7875-4cd8-a67d-7082faacafdc , Name: "Removing host(s) from cluster" Type: "CLUSTER_COMPACTION" is in state Failed
│
│   with vcf_domain.workload_domain1,
│   on wld1.tf line 134, in resource "vcf_domain" "workload_domain1":
│  134: resource "vcf_domain" "workload_domain1" {
│
╵
```

### Expected Behavior

Remove host operation on a cluster should have succeeded.

### Actual Behavior

Fails to remove because by default the vSphere HA is **OFF**.

### Steps to Reproduce

- Create a workload_domain
- Add hosts to the cluster
- Remove host from cluster  -- >  Fails here

**Comment by tenthirtyam** [comment]
Please use the markdown editor to formal the hcl and console output for readability

Reference: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by tenthirtyam** [comment]
Proper formatting applied for maintainer readability and historical context.

**Comment by spacegospod** [comment]
`high_availability_enabled` is optional and simply setting it to `true` should work around the problem.

As for the default value - it should stay `false`.
This is an optional property according to the documentation https://developer.broadcom.com/xapis/vmware-cloud-foundation-api/latest/data-structures/AdvancedOptions/
Furthermore enabling HA on a cluster should be a concious decision and should be specified explicitly by the user.

**Comment by tenthirtyam** [comment]
Closing per https://github.com/vmware/terraform-provider-vcf/issues/201#issuecomment-2259841530.
