### ISSUE TITLE
Add support for detailed workflow status

### ISSUE THREAD

**Issue by pradeep17j** [vmware/terraform-provider-vcf#204]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

When bringup is happening, the output from `terraform apply` command says:

```console
vcf_instance.sddc_instance: Still creating... [1h20m40s elapsed]
vcf_instance.sddc_instance: Still creating... [1h20m50s elapsed]
vcf_instance.sddc_instance: Still creating... [1h21m00s elapsed]
```

This does not give any insight into what is happening in the background. Also when there is a failure, we will have to login to CB or SDDC to find the point of failure.

A task API like below returns back the detailed status of sub-task in progress.
https://10.0.0.215/v1/sddcs/290051a3-1725-4edc-9df9-6e94655cec0d

The CB UI utilizes this API to display the granular detail of sub-task in progress.

The provider also should utilize this API and display the details instead of 
_"Still creating ....."_ message.

### Use Case(s)

Will help user get a granular view of sub-task in progress.

### Potential Configuration

A detailed display for long running tasks.

**Comment by pradeep17j** [comment]
The sub-task messages should look like below

Generate Security Thumbprints Input Data post-validation completed!
 Validate Security Thumbprints post-validation completed!
 Generate input for Trust Certificates post-validation completed!
 Trust Certificates post-validation completed!
 Generate input for Import SSH Keys post-validation completed!

**Comment by tenthirtyam** [comment]
#227 has been merged. 

Integration of the task tracker will need to be added on a per resource / data source as required. Once integrated, to enable the new logging one must set `TF_LOG_PROVIDER_VCF` to a valid log level.
