### ISSUE TITLE
 `d/domain`: add support to use `name`

### ISSUE THREAD

**Issue by insidepacket** [vmware/terraform-provider-vcf#207]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

When using domain data resources, support for using the name of the workload domain instead of the domain ID is preferred when retrieving a domain data resource.

### Use Case(s)

Using the domain ID is time-consuming and not aligned with common practice. We should support using the name of the workload domain to retrieve a domain data resource.

### Potential Configuration

```hcl
data "vcf_domain" "example" {
  name = var.vcf_domain_name
}
```

**Comment by burnsjared0415** [comment]
i can pick up if ok

**Comment by tenthirtyam** [comment]
Assigned to Jared Burns, VMware by Broadcom.
