### ISSUE TITLE
`r/instance`: breaking change for 4.x support

### ISSUE THREAD

**Issue by pradeep17j** [vmware/terraform-provider-vcf#208]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/terraform-provider-vcf/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.7.5

### Terraform Provider

v0.10.0

### VMware Cloud Foundation

4.x

### Description

As described in the fix for #189. 

`r/vcf_instance` will stop working for 4.x.

Please use cloud builder API to find if the version of VCF is 4.x or 5.x .
Accordingly make decision to not include `cluster_image_enabled` flag in the spec if it is 4.x.

~A fix for #189 should not introduce a breaking change for 4.x (without a major semver.)~
(spacegospod) - the provider is still under development and backwards compatibility and support is not guaranteed.
The statement that breaking changes are only allowed on major releases is not true, at least not before we hit v1.0

### Affected Resources or Data Sources

`r/vcf_instance`

### Terraform Configuration

```hcl
resource vcf_instance "example"
{
}
```

### Debug Output

Based on comment in #189 about breaking change in `r/vcf_instance` for 4.x.

### Expected Behavior

Creation of `r/vcf_instance` on 4.x should succeed.

### Actual Behavior

`terraform apply` with or without `cluster_image_enabled` can fail for 4.x.

### Steps to Reproduce

Submitting bug based on comment in #189.

Will run this workflow and update the bug.

**Comment by tenthirtyam** [comment]
Please apply formatting.

**Comment by tenthirtyam** [comment]
Formatting applied.

**Comment by spacegospod** [comment]
@tenthirtyam The breaking change was concious and intentional.
There are other changes in the provider that are likely to break 4.X support and going forward I believe we should only support 1 major version at a time.

I propose that I update the docs to reflect that we only **fully** support VCF 5.X

**Comment by tenthirtyam** [comment]
Closing as the version support is clearly provided in the README and the registry.
