### ISSUE TITLE
Add support for `d/vcf_certificate`

### ISSUE THREAD

**Issue by insidepacket** [vmware/terraform-provider-vcf#212]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add data resource for vcf_certificate that can be used in the certificate renewal use case.

### Use Case(s)

Most of the time, customers won’t change the subject attributes (e.g., CN, OU, Location, etc.) when renewing an existing certificate. If we have a certificate data source, we don’t need customers to provide these as input. This will improve the customer experience.

### Potential Configuration

```hcl
data vcf_certificate "example" {
    subjectname = var.cert_subject_name
}
```

**Comment by tenthirtyam** [comment]
David, could you kindly format the potential configuration content with the markdown and apply the hcl language?

**Comment by insidepacket** [comment]
Here you are:
```
version        = "V3"
serialNumber   = "31:00:00:00:17:a4:7f:cc:02:49:e9:19:a3:00:00:00:00:00:17"
issuedTo       = "sfo-w01-vc01.sfo.rainpole.io"
resourceType   = "VCENTER"
resourceName   = "sfo-w01-vc01.sfo.rainpole.io"
issuedBy       = "CN=rainpole-RPL-AD01-CA, DC=rainpole, DC=io"
notBefore      = "2024-07-29T11:45:00.000Z"
notAfter       = "2026-07-29T11:55:00.000Z"
signatureAlgorithm = "SHA256withRSA"

subject = {
    CN = "sfo-w01-vc01.sfo.rainpole.io"
    OU = "VCF"
    O  = "VMware Inc."
    L  = "Paris"
    ST = "Sofia-grad"
    C  = "BG"
}

subjectAlternativeName = [
    "admin@vmware.com",
    "sfo-w01-vc01.sfo.rainpole.io"
]
publicKeyAlgorithm = "RSA"
keySize        = "3072"
thumbprintAlgorithm = "SHA-256"
numberOfDaysToExpire = 728
expirationStatus = "ACTIVE"
```

**Comment by tenthirtyam** [comment]
Assigned to Ryan Johnson, VMware by Broadcom.

**Comment by insidepacket** [comment]
The update has been merged into the main branch.
