### ISSUE TITLE
With VCF 9.0 , the bringup workflow needs to be redesigned 

### ISSUE THREAD

**Issue by pradeep17j** [vmware/terraform-provider-vcf#213]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

With VCF 9.0, Unified installer / Quick start will be introduced.
With this change the Cloud builder and its APIs to create the SDDC instance will change.
The provider needs to be redesigned to be compatible with VCF 9.0.

### Use Case(s)

Accommodate product changes in VCF 9.0

### Potential Configuration

resource vcf_instance

**Comment by tenthirtyam** [comment]
Hi @pradeep17j 👋 -

Issues should reflect supported and shipping versions that the provider supports.

Planning and communications for futures versions for VMware Cloud Foundation should be managed internally.

Ryan Johnson
Distinguished Engineer, VMware by Broadcom
