### ISSUE TITLE
Incorrect `ResourceType` for NSX Edge

### ISSUE THREAD

**Issue by insidepacket** [vmware/terraform-provider-vcf#214]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/terraform-provider-vcf/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v.1.9.4

### Terraform Provider

v0.10.0

### VMware Cloud Foundation

v5

### Description

When using resource type NSX_Edge to rotate NSX Edge credentials. It can't find any NSX edge credentials although the API calls can retrieve NSX Edge system credentials. I have identified the issue: The provider requests `resourceType: NSX_EDGE` but API response suggest that the right `resourceType: NSXT_EDGE`.

### Affected Resources or Data Sources

`r/credentials`

### Terraform Configuration

https://gist.github.com/insidepacket/b549c31c581b4f9f70cda66750039dc1

### Debug Output

https://gist.github.com/insidepacket/b549c31c581b4f9f70cda66750039dc1

### Expected Behavior

Can get the NSX Edge system credentials and rotate it.

### Actual Behavior

Unable to find any NSX Edge system credentials.

### Steps to Reproduce

Step 1: stand up a VCF instance or have an existing instance.
Step 2: create the TF template
Step 3: `terraform apply` or `terraform plan`.

**Comment by tenthirtyam** [comment]
Issue seems to be from the following `const` for `ResourceTypeNsxEdge`:

https://github.com/vmware/terraform-provider-vcf/blob/b2f78510cfadd5c87ce4eb1f4879ff33c97c96ee/internal/credentials/constants.go#L9-L24

**Comment by insidepacket** [comment]
@tenthirtyam, you were faster than me to create the PR.
