### ISSUE TITLE
HCL code block  provider vcf { } is common between day0 and day1 operations

### ISSUE THREAD

**Issue by pradeep17j** [vmware/terraform-provider-vcf#251]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/terraform-provider-vcf/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.7.2

### Terraform Provider

0.11.0

### VMware Cloud Foundation

5.2.1

### Description

When doing bringup , the code block
```
provider "vcf" {
    cloud builder details
}
```
When doing day1 operations like wld create

```
provider "vcf" {
   sddc manager details
}
```

If we want to build one tf file which does all workflows like bringup , host commission ,  WLD create etc
we cannot do so because  after bringup complete , we need to change the content of provider "vcf" with sddc_m details.
Is there a work around for this ?

### Affected Resources or Data Sources

r/vcf_instance
r/vcf_workload_domain

### Terraform Configuration

Full stack VCF build

### Debug Output

This is a design issue . So no debug output

### Expected Behavior

Create full stack VCF 

### Actual Behavior

Not possible now because mid way we need to change the contents of block provider "vcf" {}

### Steps to Reproduce

It is a design issue

**Comment by tenthirtyam** [comment]
This can be done with provider aliases.

```hcl
provider "vcf" {
  alias = "cloud_builder"
  # Cloud builder details configuration
}

provider "vcf" {
  alias = "sddc_manager"
  # SDDC manager details configuration
}

resource "vcf_resource" "foo" {
  provider = vcf.cloud_builder
  # Resource configuration for Cloud Builder.
}

resource "vcf_resource" "bar" {
  provider = vcf.sddc_manager
  # Resource configuration for SDDC Manager.
}

```
