### ISSUE TITLE
Add support for management domain deployment

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/terraform-provider-vcf#38]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add support for management domain deployment / bringup.

### Use Case(s)

Adds support for the management domain bringup.

### Potential Configuration

To be determined.

> **Note**: It will need to be determined how the management domain should be managed day-two with Terraform but not allow a destroy.

**Comment by dimitarproynov** [comment]
"Note: It will need to be determined how the management domain should be managed day-two with Terraform but not allow a destroy." - Users can have a domain datasource, pointing to the MGMT Domain and add/remove/expand/shrink clusters in it.
