### ISSUE TITLE
Add support for configuration of NSX host TEP pool (static / DHCP) in `r/vcf_domain`

### ISSUE THREAD

**Issue by fieldsta** [vmware/terraform-provider-vcf#54]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add support in `r/vcf_domain` for configuring NSX host TEP pools.

### Use Case(s)

Completeness of workload domain creation with NSX.

### Potential Configuration

```json
"nsxClusterSpec":{
 "nsxTClusterSpec":{
  "geneveVlanId":####,
  "ipAddressPoolSpec":{
  "name":"<tep-pool-name>",
  "subnets":[
   {
    "ipAddressPoolRanges":[
     {
      "start":"###.###.###.###",
      "end":"###.###.###.###"
     }
    ],
    "cidr":"###.###.###.###/##",
    "gateway":"###.###.###.###"
   }
  ]
 }
}
```

**Comment by dimitarproynov** [comment]
Feature added. Will come out with v0.4.0
