### ISSUE TITLE
Add support for FQDN in ntp_servers

### ISSUE THREAD

**Issue by LifeOfBrianOC** [vmware/terraform-provider-vcf#77]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Please consider adding support for FQDN in ntp_servers when creating a VCF instance. Currently, the provider is validating for IPAddress only "validation.IsIPAddress"

### Use Case(s)

Many customers use FQDN for NTP servers, or a CNAME entry in DNS to round-robin multiple backing NTP servers

### Potential Configuration

Add additional validation for FQDN

**Comment by tenthirtyam** [comment]
Completely agree!

**Comment by dimitarproynov** [comment]
Fix is merged and will be out with the next version v0.6.0

**Comment by LifeOfBrianOC** [comment]
Awesome, thank you!
