### ISSUE TITLE
vcf_host  provider should accept a network name versus only a network_pool_id

### ISSUE THREAD

**Issue by jmac-vmw** [vmware/terraform-provider-vcf#91]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

The vcf_host resource in 0.6.0  works appropriately, however, it requires a network_pool_id, which is the actual GUID for the network pool, and not the name.  There is no way from the provider to (as far as i can tell) get the network ID, without creating a network.  

The example, shown  in (https://github.com/vmware/terraform-provider-vcf/blob/main/examples/resources/host/vcf_host.tf) gets around this because it is also creating a new  network pool and can use the vcf_network_pool.eng_pool.id for the name.  

Feature per @tenthirtyam to add a way to be able to specify an existing network pool by name so that without having to create a network pool that hosts can be added to an existing pool.  Once added, the example example can probably be updated so that it simply refers to the add host tf function, referring people to the network pool function example if they actually need to create an additional pool.

### Use Case(s)

Automating the addition of hosts to an existing network pool.

### Potential Configuration

TBD

**Comment by tenthirtyam** [comment]
Need a datasource for network pools.
